import React from 'react';
import { 
  LayoutDashboard, 
  Users, 
  Gift, 
  Package, 
  ClipboardList, 
  History,
  QrCode,
  TrendingUp,
  TrendingDown,
  Clock,
  CheckCircle2,
  XCircle,
  Truck,
  ShoppingCart,
  RefreshCw,
  BellRing
} from 'lucide-react';
import { Customer, Gift as GiftType, Product, RedemptionRequest, Activity, Order } from './types';

export const COLORS = {
  navy: '#0A192F',
  cyan: '#00B4D8',
  azure: '#0077B6',
  background: '#F8FAFC',
};

export const MENU_ITEMS = [
  { id: 'dashboard', label: { UZ: 'Boshqaruv paneli' }, icon: <LayoutDashboard className="w-5 h-5" />, path: '/' },
  { id: 'customers', label: { UZ: 'Mijozlar' }, icon: <Users className="w-5 h-5" />, path: '/customers' },
  { id: 'orders', label: { UZ: 'Ballar buyurtmasi' }, icon: <ShoppingCart className="w-5 h-5" />, path: '/orders' },
  { id: 'gifts', label: { UZ: 'Sovg\'alar' }, icon: <Gift className="w-5 h-5" />, path: '/gifts' },
  { id: 'products', label: { UZ: 'Mahsulotlar' }, icon: <Package className="w-5 h-5" />, path: '/products' },
  { id: 'qr-scans', label: { UZ: 'QR skanlar' }, icon: <QrCode className="w-5 h-5" />, path: '/qr-scans' },
  { id: 'qr-manage', label: { UZ: 'QR boshqaruv' }, icon: <QrCode className="w-5 h-5" />, path: '/qr-manage' },
  { id: 'requests', label: { UZ: 'Almashish so\'rovlari' }, icon: <ClipboardList className="w-5 h-5" />, path: '/requests' },
  { id: 'push-notifications', label: { UZ: 'Push xabarnomalar' }, icon: <BellRing className="w-5 h-5" />, path: '/push-notifications' },
  { id: 'audit', label: { UZ: 'Audit jurnali' }, icon: <History className="w-5 h-5" />, path: '/audit' },
];

export const NAV_GROUPS = [
  {
    title: { UZ: 'Umumiy ko\'rinish' },
    items: [
      { id: 'dashboard', label: { UZ: 'Boshqaruv paneli' }, icon: <LayoutDashboard className="w-5 h-5" /> },
    ]
  },
  {
    title: { UZ: 'Mijozlarni boshqarish' },
    items: [
      { id: 'customers', label: { UZ: 'Mijozlar' }, icon: <Users className="w-5 h-5" /> },
    ]
  },
  {
    title: { UZ: 'Ballar operatsiyalari' },
    items: [
      { id: 'orders', label: { UZ: 'Ballar buyurtmasi' }, icon: <ShoppingCart className="w-5 h-5" /> },
      { id: 'qr-scans', label: { UZ: 'QR skanlar' }, icon: <QrCode className="w-5 h-5" /> },
      { id: 'qr-manage', label: { UZ: 'QR boshqaruv' }, icon: <QrCode className="w-5 h-5" /> },
      { id: 'requests', label: { UZ: 'Almashish so\'rovlari' }, icon: <ClipboardList className="w-5 h-5" /> },
    ]
  },
  {
    title: { UZ: 'Katalog' },
    items: [
      { id: 'gifts', label: { UZ: 'Sovg\'alar' }, icon: <Gift className="w-5 h-5" /> },
      { id: 'products', label: { UZ: 'Mahsulotlar' }, icon: <Package className="w-5 h-5" /> },
    ]
  },
  {
    title: { UZ: 'Tizim' },
    items: [
      { id: 'push-notifications', label: { UZ: 'Push xabarnomalar' }, icon: <BellRing className="w-5 h-5" /> },
      { id: 'audit', label: { UZ: 'Audit jurnali' }, icon: <History className="w-5 h-5" /> },
    ]
  }
];

export const TRANSLATIONS = {
  UZ: {
    dashboard: 'Boshqaruv paneli',
    customers: 'Mijozlar',
    orders: 'Ballar buyurtmasi',
    gifts: 'Sovg\'alar',
    products: 'Mahsulotlar',
    requests: 'Almashish so\'rovlari',
    audit: 'Audit jurnali',
    admin: 'Admin',
    user: 'Foydalanuvchi',
    switch_to_portal: 'Mijoz portaliga o\'tish',
    jump_to: 'O\'tish...',
    operational_insights: 'Operatsion ko\'rsatkichlar',
    track_manage_loyalty: 'Sodiqlik dasturini kuzatib boring va boshqaring',
    filter_period: 'Davr filtri',
    add_entity: 'Ob\'ekt qo\'shish',
    total_customers: 'Jami mijozlar',
    points_issued: 'Berilgan ballar',
    redemptions: 'Almashuvlar',
    pending_requests: 'Kutilayotgan so\'rovlar',
    points_movement: 'Ballar harakati vaqt bo\'yicha',
    issued: 'Berilgan',
    redeemed: 'Almashilgan',
    gift_categories: 'Sovg\'a toifalari',
    total_items: 'Jami buyumlar',
    audit_activity: 'Audit va faollik',
    view_full_log: 'To\'liq jurnal',
    top_earners: 'Eng ko\'p ball to\'plaganlar',
    earned_this_month: 'Shu oyda to\'plangan',
    total_points: 'Jami ballar',
    vs_last_month: 'o\'tgan oyga nisbatan',
    search_placeholder: 'Mijozlarni qidirish...',
    add_customer: 'Mijoz qo\'shish',
    export: 'Eksport',
    full_name: 'FIO',
    phone: 'Telefon',
    status: 'Holat',
    last_updated: 'Yangilangan',
    actions: 'Harakatlar',
    close: 'Yopish',
    rows_per_page: 'Sahifada',
    go_to_page: 'Sahifaga o‘tish',
    view_profile: 'Profilni ochish →',
    note: 'Izoh',
    reversal_reason: 'Bekor qilish sababi',
    points_reconciliation: 'Ballar hisobi',
    reversal_reason_placeholder: 'Nima uchun bekor qilinmoqda?',
    active: 'Faol',
    blocked: 'Bloklangan',
    points: 'Ballar',
    earned: 'To\'plangan',
    all_customers: 'Barcha mijozlar',
    customer_details: 'Mijoz tafsilotlari',
    edit: 'Tahrirlash',
    block: 'Bloklash',
    unblock: 'Blokdan chiqarish',
    delete: 'O\'chirish',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    confirm: 'Tasdiqlash',
    draft: 'Qoralama',
    confirmed: 'Tasdiqlangan',
    cancelled: 'Bekor qilingan',
    pending: 'Kutilmoqda',
    approved: 'Tasdiqlangan',
    rejected: 'Rad etilgan',
    shipped: 'Yuborilgan',
    completed: 'Yakunlangan',
    date: 'Sana',
    customer: 'Mijoz',
    items: 'Mahsulotlar',
    created_by: 'Tomonidan yaratilgan',
    new_order: 'Yangi buyurtma',
    gift_name: 'Sovg\'a nomi',
    points_used: 'Ishlatilgan ballar',
    operator: 'Operator',
    type: 'Turi',
    reject_reason: 'Rad etish sababi',
    approve: 'Tasdiqlash',
    reject: 'Rad etish',
    stock: 'Ombor',
    category: 'Toifa',
    sku: 'SKU / artikul',
    points_cost: 'Narxi (ball)',
    is_active: 'Faol',
    add_gift: 'Sovg\'a qo\'shish',
    add_product: 'Mahsulot qo\'shish',
    points_value: 'Qiymati (ball)',
    my_points: 'Mening ballarim',
    available_gifts: 'Mavjud sovg\'alar',
    redeem: 'Almashish',
    my_requests: 'Mening so\'rovlarim',
    welcome_back: 'Xush kelibsiz',
    logout: 'Chiqish',
    switch_view: 'Ko\'rinishni o\'zgartirish',
    history: 'Tarix',
    no_data: 'Ma\'lumot topilmadi',
    loading: 'Yuklanmoqda...',
    success: 'Muvaffaqiyat',
    error: 'Xato',
    new_request: 'Yangi almashish so\'rovi',
    manual_issuance: 'Qo\'lda operatsion berish',
    select_customer: 'Mijozni tanlang',
    select_gift: 'Sovg\'ani tanlang',
    confirmation: 'Dastlabki ko\'rinish',
    back: 'Orqaga',
    next: 'Keyingi',
    create_approve: 'Yaratish va tasdiqlash',
    operational_queue: 'Operatsion navbat',
    manage_lifecycle: 'Almashish hayotiy tsiklini va qo\'lda so\'rovlarni boshqarish',
    new_manual_request: 'Yangi qo\'lda so\'rov',
    queue_inspector: 'Navbat inspektori',
    select_request_sidebar: 'Tafsilotlarni ko\'rish va jarayonlarni boshqarish uchun yon paneldan so\'rovni tanlang.',
    confirm_approval: 'Tasdiqlashni tasdiqlang',
    execute_approval: 'Tasdiqlashni bajarish',
    request_rejection: 'So\'rovni rad etish',
    specify_reject_reason: 'Iltimos, rad etish sababini ko\'rsating. Mijoz xabardor qilinadi.',
    confirm_reject: 'Rad etishni tasdiqlash',
    insufficient_points: 'Ballar yetarli emas',
    low_stock: 'Omborda kam',
    product_mapping: 'Mahsulotlarni bog\'lash',
    assign_points: 'IRIZON tijorat mahsulotlariga ball qiymatlarini tayinlash',
    bonus_value: 'Bonus qiymati',
    bonus_issuance: 'Bonus ballarini berish',
    manage_bonus: 'Mijoz hisoblariga qo\'lda bonus qo\'shishni boshqarish',
    export_orders: 'Buyurtmalarni eksport qilish',
    create_bonus_order: 'Bonus buyurtmasini yaratish',
    filter_status: 'Holat filtri',
    all_admins: 'Barcha adminlar',
    order_id: 'Buyurtma ID',
    date_time: 'Sana / Vaqt',
    points_added: 'Qo\'shilgan ballar',
    order_details: 'Buyurtma tafsilotlari',
    products_issued: 'Berilgan mahsulotlar',
    unit_points: 'Birlik ballari',
    qty: 'Soni',
    total: 'Jami',
    grand_total: 'Umumiy jami',
    admin_note: 'Admin eslatmasi',
    duplicate_order: 'Buyurtmani nusxalash',
    confirm_now: 'Hozir tasdiqlash',
    bonus_workflow: 'Bonus berish jarayoni',
    step_customer: '1-qadam: Mijozni tanlang',
    active_selection: 'Faol tanlov',
    current_balance: 'Joriy balans',
    lifetime_earned: 'Jami to\'plangan',
    last_activity: 'Oxirgi faollik',
    no_customers_found: 'Mijoz topilmadi',
    type_to_search: 'Mijozni qidirish uchun yozing...',
    next_add_products: 'Keyingi: Mahsulotlarni qo\'shish',
    step_products: '2-qadam: Mahsulotlar va miqdor',
    issuing_to: 'Berilmoqda:',
    row_total: 'Satr jami',
    select_product: 'Mahsulotni tanlang...',
    add_next_product: 'Keyingi mahsulotni qo\'shish',
    items_count: 'Mahsulotlar soni',
    target_balance_after: 'Keyingi balans',
    next_review: 'Keyingi: Ko\'rib chiqish va tasdiqlash',
    step_review: '3-qadam: Yakuniy ko\'rib chiqish',
    account_update_summary: 'Hisobni yangilash xulosasi',
    points_to_add: 'Qo\'shiladigan ballar:',
    new_total_balance: 'Yangi umumiy balans:',
    product_breakdown: 'Mahsulotlar taqsimoti',
    issuance_reason_placeholder: 'Berish sababi (masalan: Buyurtma kechikkani uchun kompensatsiya...)',
    safety_confirmation: 'Xavfsizlik tasdig\'i talab qilinadi',
    safety_confirmation_desc: 'Ushbu harakat mijozning ball balansini darhol yangilaydi. Hisobdorlik uchun audit jurnalida yozuvlar yaratiladi.',
    safety_confirmation_label: 'Barcha tafsilotlar to\'g\'riligini tasdiqlayman va ushbu ball berishni verifikatsiya qilaman.',
    back_to_edit: 'Tahrirlashga qaytish',
    confirm_add_points: 'Tasdiqlash va ballarni qo\'shish',
    min: 'Min',
    max: 'Maks',
    points_range: 'Ballar oralig\'i',
    earned_range: 'To\'plangan ballar oralig\'i',
    redeemed_range: 'Almashilgan ballar oralig\'i',
    add_points_modal: 'Hisobga ball qo\'shish',
    amount: 'Miqdor',
    reason: 'Sabab',
    prev: 'Oldingi',
    showing: 'Ko\'rsatilmoqda',
    of: 'dan',
    totals: 'Jami',
    reconciliation: 'Ballar bo\'yicha solishtirish',
    period_from: 'Sana dan',
    period_to: 'Sana gacha',
    opening_balance: 'Boshlang\'ich qoldiq',
    closing_balance: 'Yakuniy qoldiq',
    total_earned_period: 'Jami to\'plangan',
    total_spent_period: 'Jami ishlatilgan',
    order_count: 'Buyurtmalar soni',
    gift_count: 'Sovg\'alar soni',
    document_name: 'Hujjat nomi',
    earned_dt: 'To\'plangan (DT)',
    spent_kt: 'Ishlatilgan (KT)',
    balance_after: 'Operatsiyadan keyingi balans',
    total_for_period: 'Davr uchun JAMI',
    print: 'Chop etish',
    export_pdf: 'PDF eksport',
    audit_log: 'Audit jurnali',
    company_name: 'Kompaniya nomi',
    points_name: 'Ballar nomi (masalan: Kreditlar)',
    points_expiry: 'Ballar muddati (oy)',
    min_redemption: 'Minimal almashish miqdori',
    admin_roles: 'Admin rollari',
    add_admin: 'Admin qo\'shish',
    activity_type: 'Faollik turi',
    details: 'Tafsilotlar',
    user_agent: 'User Agent',
    ip_address: 'IP manzil',
    all: 'Barchasi',
    request_id: 'So\'rov ID',
    gift: 'Sovg\'a',
    unit: 'dona',
    balance_after_redemption: 'Almashishdan keyingi balans',
    client_balance_info: 'Mijoz balansi',
    available_points: 'Mavjud ballar',
    out_of_stock: 'Tugagan',
    process_timeline: 'Jarayon tarixi',
    request_initiated: 'So\'rov yaratildi:',
    processed_by: 'Bajaruvchi',
    transitioned_to: 'Yangi status:',
    confirm_status_change: 'Status o\'zgarishini tasdiqlang',
    status_change_warning: 'Tasdiqlanganda mijoz balansidan ballar yechiladi va sovg\'a zaxirasi kamayadi. Rad etilganda ballar qaytariladi.',
    confirm_action_correct: 'Amal to\'g\'riligini tasdiqlayman',
    reject_reason_placeholder: 'Rad etish sababini yozing...',
    loyalty_analytics: 'Sodiqlik tahlili',
    new_this_month: 'Bu oy yangi',
    active_30d: 'Faol (30 kun)',
    not_returned_90d: '90+ kun qaytmagan',
    avg_lifetime: 'O\'rtacha faollik muddati',
    tier_distribution: 'Darajalar',
    customer_segments: 'Segmentlar',
    seg_Champion: 'Chempion',
    seg_Loyal: 'Sodiq',
    seg_New: 'Yangi',
    'seg_At-Risk': 'Xavf ostida',
    seg_Dormant: 'Uxlab qolgan',
    seg_Inactive: 'Nofaol',
    new_bonus_order: 'Yangi bonus buyurtmasi',
    manual_bonus: 'Qo\'lda bonus',
    manual_bonus_hint: 'Katalogsiz ixtiyoriy ball berish',
    enter_points: 'Ballarni kiriting',
    product: 'Mahsulot',
    quantity: 'Miqdor',
    balance: 'Balans',
    review: 'Ko\'rib chiqish',
    review_confirm: 'Ko\'rib chiqish va tasdiqlash',
    admin_note_placeholder: 'Admin eslatmasi (ixtiyoriy)...',
    confirm_verify_issuance: 'Ma\'lumotlar to\'g\'riligini tekshirdim va berishni tasdiqlayman',
    view_order: 'Buyurtmani ko\'rish',
    reset_all: 'Davrni tiklash',
  }
};

export const DUMMY_CUSTOMERS: Customer[] = [
  { id: 'C-1001', fullName: 'Alexander Petrov', phone: '+998 90 123 45 67', totalPoints: 4500, pointsEarned: 12000, pointsRedeemed: 7500, status: 'active', lastUpdated: '2023-11-20' },
  { id: 'C-1002', fullName: 'Dilshod Karimov', phone: '+998 93 321 65 43', totalPoints: 1200, pointsEarned: 5000, pointsRedeemed: 3800, status: 'active', lastUpdated: '2023-11-21' },
  { id: 'C-1003', fullName: 'Elena Ivanova', phone: '+998 94 999 00 11', totalPoints: 8900, pointsEarned: 15000, pointsRedeemed: 6100, status: 'blocked', lastUpdated: '2023-11-19' },
  { id: 'C-1004', fullName: 'Azizbek Toshpulotov', phone: '+998 97 777 88 99', totalPoints: 340, pointsEarned: 1000, pointsRedeemed: 660, status: 'active', lastUpdated: '2023-11-22' },
];

export const DUMMY_GIFTS: GiftType[] = [
  { 
    id: 'G-2001', 
    name: { UZ: 'Premium termos' },
    description: { UZ: 'Ichimliklarni 24 soat issiq saqlaydi.' },
    pointsCost: 500, category: 'Lifestyle', stock: 12, isActive: true, image: 'https://picsum.photos/400/300?random=1' 
  },
  { 
    id: 'G-2002', 
    name: { UZ: 'Simsiz quloqchinlar' },
    description: { UZ: 'Yuqori sifatli ovoz.' },
    pointsCost: 1200, category: 'Tech', stock: 5, isActive: true, image: 'https://picsum.photos/400/300?random=2' 
  },
  { 
    id: 'G-2003', 
    name: { UZ: 'Charm daftar' },
    description: { UZ: 'A5 Tabiiy charm muqova.' },
    pointsCost: 300, category: 'Stationary', stock: 0, isActive: false, image: 'https://picsum.photos/400/300?random=3' 
  },
];

export const DUMMY_PRODUCTS: Product[] = [
  { id: 'P-3001', name: { UZ: 'Quyosh paneli X5' }, pointsValue: 50, isActive: true, category: 'Energy' },
  { id: 'P-3002', name: { UZ: 'Aqlli invertor Pro' }, pointsValue: 120, isActive: true, category: 'Electronics' },
];

export const DUMMY_REQUESTS: RedemptionRequest[] = [
  { id: 'REQ-5001', date: '2023-11-22 14:30', customerId: 'C-1001', customerName: 'Alexander Petrov', giftId: 'G-2001', giftName: 'Premium Thermos', pointsUsed: 500, status: 'Pending', requestType: 'Customer', giftImage: 'https://picsum.photos/400/300?random=1' },
  { id: 'REQ-5002', date: '2023-11-21 09:15', customerId: 'C-1002', customerName: 'Dilshod Karimov', giftId: 'G-2002', giftName: 'Wireless Headphones', pointsUsed: 1200, status: 'Approved', operator: 'Admin-Z', requestType: 'Customer', giftImage: 'https://picsum.photos/400/300?random=2' },
  { id: 'REQ-5003', date: '2023-11-20 18:00', customerId: 'C-1004', customerName: 'Azizbek Toshpulotov', giftId: 'G-2003', giftName: 'Leather Notebook', pointsUsed: 300, status: 'Rejected', operator: 'Admin-X', rejectReason: 'Out of stock indefinitely.', requestType: 'Customer', giftImage: 'https://picsum.photos/400/300?random=3' },
  { id: 'REQ-5004', date: '2023-11-23 11:00', customerId: 'C-1004', customerName: 'Azizbek Toshpulotov', giftId: 'G-2002', giftName: 'Wireless Headphones', pointsUsed: 1200, status: 'Pending', requestType: 'Admin', giftImage: 'https://picsum.photos/400/300?random=2' },
];

export const DUMMY_ORDERS: Order[] = [
  {
    id: 'ORD-9001',
    date: '2023-11-22 10:00',
    customerId: 'C-1001',
    customerName: 'Alexander Petrov',
    totalPoints: 1500,
    itemsCount: 2,
    createdBy: 'Admin-X',
    status: 'Confirmed',
    items: [
      { id: 'ITM-1', productId: 'P-3001', productName: 'Solar Panel X5', pointsPerUnit: 50, quantity: 10, totalPoints: 500 },
      { id: 'ITM-2', productId: 'P-3002', productName: 'Smart Inverter Pro', pointsPerUnit: 120, quantity: 8, totalPoints: 1000 },
    ]
  },
  {
    id: 'ORD-9002',
    date: '2023-11-22 11:30',
    customerId: 'C-1002',
    customerName: 'Dilshod Karimov',
    totalPoints: 250,
    itemsCount: 1,
    createdBy: 'Admin-Z',
    status: 'Draft',
    items: [
      { id: 'ITM-3', productId: 'P-3001', productName: 'Solar Panel X5', pointsPerUnit: 50, quantity: 5, totalPoints: 250 },
    ]
  },
  {
    id: 'ORD-9003',
    date: '2023-10-15 09:00',
    customerId: 'C-1001',
    customerName: 'Alexander Petrov',
    totalPoints: 5000,
    itemsCount: 1,
    createdBy: 'Admin-X',
    status: 'Confirmed',
    items: [
      { id: 'ITM-4', productId: 'P-3002', productName: 'Smart Inverter Pro', pointsPerUnit: 120, quantity: 42, totalPoints: 5040 },
    ]
  },
  {
    id: 'ORD-9004',
    date: '2023-09-01 14:00',
    customerId: 'C-1001',
    customerName: 'Alexander Petrov',
    totalPoints: 2000,
    itemsCount: 1,
    createdBy: 'Admin-Z',
    status: 'Confirmed',
    items: [
      { id: 'ITM-5', productId: 'P-3001', productName: 'Solar Panel X5', pointsPerUnit: 50, quantity: 40, totalPoints: 2000 },
    ]
  }
];

export const DUMMY_ACTIVITIES: Activity[] = [
  { id: 'ACT-001', type: 'customer_added', description: 'New customer Elena Ivanova added to system', time: '2 hours ago', user: 'Admin-X' },
  { id: 'ACT-002', type: 'gift_redeemed', description: 'Alexander Petrov redeemed Wireless Headphones', time: '5 hours ago', user: 'System' },
  { id: 'ACT-003', type: 'request_status_change', description: 'Request REQ-5002 approved by Admin-Z', time: '1 day ago', user: 'Admin-Z' },
  { id: 'ACT-004', type: 'order_confirmed', description: 'Bonus order ORD-9001 confirmed for Alexander Petrov', time: '2 days ago', user: 'Admin-X' },
];

export const STATUS_CONFIG = {
  Pending: { color: 'bg-amber-100 text-amber-700 border-amber-200', icon: <Clock className="w-3 h-3" /> },
  Approved: { color: 'bg-emerald-100 text-emerald-700 border-emerald-200', icon: <CheckCircle2 className="w-3 h-3" /> },
  Rejected: { color: 'bg-rose-100 text-rose-700 border-rose-200', icon: <XCircle className="w-3 h-3" /> },
  Shipped: { color: 'bg-blue-100 text-blue-700 border-blue-200', icon: <Truck className="w-3 h-3" /> },
  Completed: { color: 'bg-slate-100 text-slate-700 border-slate-200', icon: <CheckCircle2 className="w-3 h-3" /> },
};
