import React from 'react';
import { 
  LayoutDashboard, 
  Users, 
  Gift, 
  Package, 
  ClipboardList, 
  History,
  QrCode,
  TrendingUp,
  TrendingDown,
  Clock,
  CheckCircle2,
  XCircle,
  Truck,
  ShoppingCart,
  RefreshCw,
  BellRing
} from 'lucide-react';
import { Customer, Gift as GiftType, Product, RedemptionRequest, Activity, Order } from './types';

export const COLORS = {
  navy: '#0A192F',
  cyan: '#00B4D8',
  azure: '#0077B6',
  background: '#F8FAFC',
};

export const MENU_ITEMS = [
  { id: 'dashboard', label: { EN: 'Dashboard', RU: 'Панель управления', UZ: 'Boshqaruv paneli' }, icon: <LayoutDashboard className="w-5 h-5" />, path: '/' },
  { id: 'customers', label: { EN: 'Customers', RU: 'Клиенты', UZ: 'Mijozlar' }, icon: <Users className="w-5 h-5" />, path: '/customers' },
  { id: 'orders', label: { EN: 'Point Orders', RU: 'Заказы баллов', UZ: 'Ballar buyurtmasi' }, icon: <ShoppingCart className="w-5 h-5" />, path: '/orders' },
  { id: 'gifts', label: { EN: 'Gifts', RU: 'Подарки', UZ: 'Sovg\'alar' }, icon: <Gift className="w-5 h-5" />, path: '/gifts' },
  { id: 'products', label: { EN: 'Products', RU: 'Продукты', UZ: 'Mahsulotlar' }, icon: <Package className="w-5 h-5" />, path: '/products' },
  { id: 'qr-scans', label: { EN: 'QR Scans', RU: 'QR сканы', UZ: 'QR skanlar' }, icon: <QrCode className="w-5 h-5" />, path: '/qr-scans' },
  { id: 'qr-manage', label: { EN: 'QR Management', RU: 'QR управление', UZ: 'QR boshqaruv' }, icon: <QrCode className="w-5 h-5" />, path: '/qr-manage' },
  { id: 'requests', label: { EN: 'Redemption Requests', RU: 'Запросы на подарки', UZ: 'Almashish so\'rovlari' }, icon: <ClipboardList className="w-5 h-5" />, path: '/requests' },
  { id: 'push-notifications', label: { EN: 'Push Notifications', RU: 'Push уведомления', UZ: 'Push xabarnomalar' }, icon: <BellRing className="w-5 h-5" />, path: '/push-notifications' },
  { id: 'audit', label: { EN: 'Audit Log', RU: 'Журнал аудита', UZ: 'Audit jurnali' }, icon: <History className="w-5 h-5" />, path: '/audit' },
];

export const NAV_GROUPS = [
  {
    title: { EN: 'Overview', RU: 'Обзор', UZ: 'Umumiy ko\'rinish' },
    items: [
      { id: 'dashboard', label: { EN: 'Dashboard', RU: 'Панель управления', UZ: 'Boshqaruv paneli' }, icon: <LayoutDashboard className="w-5 h-5" /> },
    ]
  },
  {
    title: { EN: 'Customer Management', RU: 'Управление клиентами', UZ: 'Mijozlarni boshqarish' },
    items: [
      { id: 'customers', label: { EN: 'Customers', RU: 'Клиенты', UZ: 'Mijozlar' }, icon: <Users className="w-5 h-5" /> },
    ]
  },
  {
    title: { EN: 'Points Operations', RU: 'Операции с баллами', UZ: 'Ballar operatsiyalari' },
    items: [
      { id: 'orders', label: { EN: 'Point Orders', RU: 'Заказы баллов', UZ: 'Ballar buyurtmasi' }, icon: <ShoppingCart className="w-5 h-5" /> },
      { id: 'qr-scans', label: { EN: 'QR Scans', RU: 'QR сканы', UZ: 'QR skanlar' }, icon: <QrCode className="w-5 h-5" /> },
      { id: 'qr-manage', label: { EN: 'QR Management', RU: 'QR управление', UZ: 'QR boshqaruv' }, icon: <QrCode className="w-5 h-5" /> },
      { id: 'requests', label: { EN: 'Redemption Requests', RU: 'Запросы на подарки', UZ: 'Almashish so\'rovlari' }, icon: <ClipboardList className="w-5 h-5" /> },
    ]
  },
  {
    title: { EN: 'Catalog', RU: 'Каталог', UZ: 'Katalog' },
    items: [
      { id: 'gifts', label: { EN: 'Gifts', RU: 'Подарки', UZ: 'Sovg\'alar' }, icon: <Gift className="w-5 h-5" /> },
      { id: 'products', label: { EN: 'Products', RU: 'Продукты', UZ: 'Mahsulotlar' }, icon: <Package className="w-5 h-5" /> },
    ]
  },
  {
    title: { EN: 'System', RU: 'Система', UZ: 'Tizim' },
    items: [
      { id: 'push-notifications', label: { EN: 'Push Notifications', RU: 'Push уведомления', UZ: 'Push xabarnomalar' }, icon: <BellRing className="w-5 h-5" /> },
      { id: 'audit', label: { EN: 'Audit Log', RU: 'Журнал аудита', UZ: 'Audit jurnali' }, icon: <History className="w-5 h-5" /> },
    ]
  }
];

export const TRANSLATIONS = {
  EN: {
    dashboard: 'Dashboard',
    customers: 'Customers',
    orders: 'Point Orders',
    gifts: 'Gifts',
    products: 'Products',
    requests: 'Redemption Requests',
    audit: 'Audit Log',
    admin: 'Admin',
    user: 'User',
    switch_to_portal: 'Switch to Customer Portal',
    jump_to: 'Jump to...',
    operational_insights: 'Operational Insights',
    track_manage_loyalty: 'Track and manage your customer loyalty program',
    filter_period: 'Filter Period',
    add_entity: 'Add Entity',
    total_customers: 'Total Customers',
    points_issued: 'Points Issued',
    redemptions: 'Redemptions',
    pending_requests: 'Pending Requests',
    points_movement: 'Points Movement Over Time',
    issued: 'Issued',
    redeemed: 'Redeemed',
    gift_categories: 'Gift Categories',
    total_items: 'Total Items',
    audit_activity: 'Audit & Activity',
    view_full_log: 'View Full Log',
    top_earners: 'Top Points Earners',
    earned_this_month: 'Earned this month',
    total_points: 'Total Points',
    vs_last_month: 'vs last month',
    search_placeholder: 'Search customers...',
    add_customer: 'Add Customer',
    export: 'Export',
    full_name: 'Full Name',
    phone: 'Phone',
    status: 'Status',
    last_updated: 'Last Updated',
    actions: 'Actions',
    active: 'Active',
    blocked: 'Blocked',
    points: 'Points',
    earned: 'Earned',
    all_customers: 'All Customers',
    customer_details: 'Customer Details',
    edit: 'Edit',
    block: 'Block',
    unblock: 'Unblock',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    draft: 'Draft',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    shipped: 'Shipped',
    completed: 'Completed',
    date: 'Date',
    customer: 'Customer',
    items: 'Items',
    created_by: 'Created By',
    new_order: 'New Order',
    gift_name: 'Gift Name',
    points_used: 'Points Used',
    operator: 'Operator',
    type: 'Type',
    reject_reason: 'Reject Reason',
    approve: 'Approve',
    reject: 'Reject',
    stock: 'Stock',
    category: 'Category',
    points_cost: 'Points Cost',
    is_active: 'Is Active',
    add_gift: 'Add Gift',
    add_product: 'Add Product',
    points_value: 'Points Value',
    my_points: 'My Points',
    available_gifts: 'Available Gifts',
    redeem: 'Redeem',
    my_requests: 'My Requests',
    welcome_back: 'Welcome back',
    logout: 'Logout',
    switch_view: 'Switch View',
    history: 'History',
    no_data: 'No data found',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    new_request: 'New Redemption Request',
    manual_issuance: 'Manual operational issuance',
    select_customer: 'Select Customer',
    select_gift: 'Select Reward Gift',
    confirmation: 'Confirmation Preview',
    back: 'Back',
    next: 'Next',
    create_approve: 'Create & Approve',
    operational_queue: 'Operational Queue',
    manage_lifecycle: 'Manage redemption lifecycle and manual requests',
    new_manual_request: 'New Manual Request',
    queue_inspector: 'Queue Inspector',
    select_request_sidebar: 'Select a request from the sidebar to inspect operational details and handle workflows.',
    confirm_approval: 'Confirm Approval',
    execute_approval: 'Execute Approval',
    request_rejection: 'Request Rejection',
    specify_reject_reason: 'Please specify the exact reason for rejection. The customer will be notified.',
    confirm_reject: 'Confirm Reject',
    insufficient_points: 'Insufficient Points',
    low_stock: 'Low Stock',
    product_mapping: 'Product Mapping',
    assign_points: 'Assign point values to IRIZON commercial products',
    bonus_value: 'Bonus Value',
    bonus_issuance: 'Bonus Point Issuance',
    manage_bonus: 'Manage manual bonus additions to customer accounts',
    export_orders: 'Export Orders',
    create_bonus_order: 'Create Bonus Order',
    filter_status: 'Filter Status',
    all_admins: 'All Admins',
    order_id: 'Order ID',
    date_time: 'Date / Time',
    points_added: 'Points Added',
    order_details: 'Order Details',
    products_issued: 'Products Issued',
    unit_points: 'Unit Points',
    qty: 'Qty',
    total: 'Total',
    grand_total: 'Grand Total',
    admin_note: 'Admin Note',
    duplicate_order: 'Duplicate Order',
    confirm_now: 'Confirm Now',
    bonus_workflow: 'Bonus Issuance Workflow',
    step_customer: 'Step 1: Select Target Customer',
    active_selection: 'Active Selection',
    current_balance: 'Current Balance',
    lifetime_earned: 'Lifetime Earned',
    last_activity: 'Last Activity',
    no_customers_found: 'No customers found matching',
    type_to_search: 'Type to search for a customer...',
    next_add_products: 'Next: Add Products',
    step_products: 'Step 2: Product Mapping & Quantities',
    issuing_to: 'Issuing to:',
    row_total: 'Row Total',
    select_product: 'Select a product...',
    add_next_product: 'Add Next Product',
    items_count: 'Items Count',
    target_balance_after: 'Target Balance After',
    next_review: 'Next: Review & Confirm',
    step_review: 'Step 3: Final Review',
    account_update_summary: 'Account Update Summary',
    points_to_add: 'Points to Add:',
    new_total_balance: 'New Total Balance:',
    product_breakdown: 'Product Breakdown',
    issuance_reason_placeholder: 'Reason for issuance (e.g. Compensation for order delay...)',
    safety_confirmation: 'Safety Confirmation Required',
    safety_confirmation_desc: "This action will immediately update the customer's point balance. Immunte records will be created in the audit log for accountability.",
    safety_confirmation_label: 'I confirm that all details are correct and verify this point issuance.',
    back_to_edit: 'Back to Edit',
    confirm_add_points: 'Confirm & Add Points',
    min: 'Min',
    max: 'Max',
    points_range: 'Points Range',
    earned_range: 'Earned Range',
    redeemed_range: 'Redeemed Range',
    add_points_modal: 'Add Points to Account',
    amount: 'Amount',
    reason: 'Reason',
    prev: 'Prev',
    showing: 'Showing',
    of: 'of',
    totals: 'Totals',
    reconciliation: 'Reconciliation Statement',
    period_from: 'Date From',
    period_to: 'Date To',
    opening_balance: 'Opening Balance',
    closing_balance: 'Closing Balance',
    total_earned_period: 'Total Earned',
    total_spent_period: 'Total Spent',
    order_count: 'Order Count',
    gift_count: 'Gift Count',
    document_name: 'Document Name',
    earned_dt: 'Earned (DT)',
    spent_kt: 'Spent (KT)',
    balance_after: 'Balance After',
    total_for_period: 'TOTAL for period',
    print: 'Print',
    export_pdf: 'Export PDF',
    edit_order: 'Edit Order',
    delete_order: 'Delete Order',
    view_order: 'View Order',
    old_total: 'Old Total',
    new_total: 'New Total',
    difference: 'Difference',
    change_reason: 'Reason for change',
    change_impact: 'This change will affect the customer balance by:',
    delete_confirmation_draft: 'Delete order {id}? This action cannot be undone.',
    delete_confirmation_confirmed: 'Deleting this order will subtract {points} points from the customer balance.',
    understand_balance_change: 'I understand that the balance will change.',
    confirm_delete: 'Confirm Delete',
    all: 'All',
    request_id: 'Request ID',
    balance_after_redemption: 'Balance After',
    gift: 'Gift',
    bulk_approve: 'Bulk Approve',
    bulk_reject: 'Bulk Reject',
    process_timeline: 'Process Timeline',
    client_balance_info: 'Client Balance Info',
    confirm_status_change: 'Confirm Status Change',
    status_change_warning: 'This will affect points and stock.',
    available_points: 'Available Points',
    out_of_stock: 'Out of Stock',
    selected: 'selected',
    unit: 'unit',
    request_initiated: 'Request Initiated',
    transitioned_to: 'Transitioned to',
    processed_by: 'Processed by',
    confirm_action_correct: 'I confirm this action is correct.',
    reject_reason_placeholder: 'Specify why this request is being rejected...',
    audit_log: 'Audit Log',
    company_name: 'Company Name',
    points_name: 'Points Name (e.g. Credits)',
    points_expiry: 'Points Expiry (Months)',
    min_redemption: 'Min Redemption Amount',
    admin_roles: 'Admin Roles',
    add_admin: 'Add Admin',
    activity_type: 'Activity Type',
    details: 'Details',
    user_agent: 'User Agent',
    ip_address: 'IP Address',
  },
  RU: {
    dashboard: 'Панель управления',
    customers: 'Клиенты',
    orders: 'Заказы баллов',
    gifts: 'Подарки',
    products: 'Продукты',
    requests: 'Запросы на подарки',
    audit: 'Журнал аудита',
    admin: 'Админ',
    user: 'Пользователь',
    switch_to_portal: 'Перейти в портал клиента',
    jump_to: 'Перейти к...',
    operational_insights: 'Операционные показатели',
    track_manage_loyalty: 'Отслеживайте и управляйте программой лояльности',
    filter_period: 'Фильтр периода',
    add_entity: 'Добавить объект',
    total_customers: 'Всего клиентов',
    points_issued: 'Выдано баллов',
    redemptions: 'Обмены',
    pending_requests: 'Ожидающие заявки',
    points_movement: 'Движение баллов во времени',
    issued: 'Выдано',
    redeemed: 'Обменено',
    gift_categories: 'Категории подарков',
    total_items: 'Всего предметов',
    audit_activity: 'Аудит и активность',
    view_full_log: 'Весь журнал',
    top_earners: 'Топ по баллам',
    earned_this_month: 'Заработано в этом месяце',
    total_points: 'Всего баллов',
    vs_last_month: 'чем в прошлом месяце',
    search_placeholder: 'Поиск клиентов...',
    add_customer: 'Добавить клиента',
    export: 'Экспорт',
    full_name: 'ФИО',
    phone: 'Телефон',
    status: 'Статус',
    last_updated: 'Обновлено',
    actions: 'Действия',
    active: 'Активен',
    blocked: 'Заблокирован',
    points: 'Баллы',
    earned: 'Заработано',
    all_customers: 'Все клиенты',
    customer_details: 'Детали клиента',
    edit: 'Изменить',
    block: 'Блок',
    unblock: 'Разблок',
    delete: 'Удалить',
    save: 'Сохранить',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    draft: 'Черновик',
    confirmed: 'Подтвержден',
    cancelled: 'Отменен',
    pending: 'Ожидает',
    approved: 'Одобрен',
    rejected: 'Отклонен',
    shipped: 'Отправлен',
    completed: 'Завершен',
    date: 'Дата',
    customer: 'Клиент',
    items: 'Товары',
    created_by: 'Создал',
    new_order: 'Новый заказ',
    gift_name: 'Название подарка',
    points_used: 'Использовано баллов',
    operator: 'Оператор',
    type: 'Тип',
    reject_reason: 'Причина отказа',
    approve: 'Одобрить',
    reject: 'Отклонить',
    stock: 'Склад',
    category: 'Категория',
    points_cost: 'Стоимость (баллы)',
    is_active: 'Активен',
    add_gift: 'Добавить подарок',
    add_product: 'Добавить продукт',
    points_value: 'Ценность (баллы)',
    my_points: 'Мои баллы',
    available_gifts: 'Доступные подарки',
    redeem: 'Обменять',
    my_requests: 'Мои заявки',
    welcome_back: 'С возвращением',
    logout: 'Выйти',
    switch_view: 'Сменить вид',
    history: 'История',
    no_data: 'Данные не найдены',
    loading: 'Загрузка...',
    success: 'Успех',
    error: 'Ошибка',
    new_request: 'Новая заявка на обмен',
    manual_issuance: 'Ручная операционная выдача',
    select_customer: 'Выберите клиента',
    select_gift: 'Выберите подарок',
    confirmation: 'Предварительный просмотр',
    back: 'Назад',
    next: 'Далее',
    create_approve: 'Создать и одобрить',
    operational_queue: 'Операционная очередь',
    manage_lifecycle: 'Управление жизненным циклом обмена и ручными запросами',
    new_manual_request: 'Новая ручная заявка',
    queue_inspector: 'Инспектор очереди',
    select_request_sidebar: 'Выберите заявку в боковой панели для просмотра деталей и управления рабочими процессами.',
    confirm_approval: 'Подтвердить одобрение',
    execute_approval: 'Выполнить одобрение',
    request_rejection: 'Отклонение заявки',
    specify_reject_reason: 'Пожалуйста, укажите точную причину отказа. Клиент будет уведомлен.',
    confirm_reject: 'Подтвердить отказ',
    insufficient_points: 'Недостаточно баллов',
    low_stock: 'Мало на складе',
    product_mapping: 'Сопоставление продуктов',
    assign_points: 'Назначение баллов коммерческим продуктам IRIZON',
    bonus_value: 'Бонусная ценность',
    bonus_issuance: 'Выдача бонусных баллов',
    manage_bonus: 'Управление ручным добавлением бонусов на счета клиентов',
    export_orders: 'Экспорт заказов',
    create_bonus_order: 'Создать бонусный заказ',
    filter_status: 'Фильтр статуса',
    all_admins: 'Все админы',
    order_id: 'ID заказа',
    date_time: 'Дата / Время',
    points_added: 'Добавлено баллов',
    order_details: 'Детали заказа',
    products_issued: 'Выданные продукты',
    unit_points: 'Баллы за ед.',
    qty: 'Кол-во',
    total: 'Итого',
    grand_total: 'Общий итог',
    admin_note: 'Заметка админа',
    duplicate_order: 'Дублировать заказ',
    confirm_now: 'Подтвердить сейчас',
    bonus_workflow: 'Процесс выдачи бонусов',
    step_customer: 'Шаг 1: Выберите целевого клиента',
    active_selection: 'Активный выбор',
    current_balance: 'Текущий баланс',
    lifetime_earned: 'Заработано всего',
    last_activity: 'Последняя активность',
    no_customers_found: 'Клиенты не найдены по запросу',
    type_to_search: 'Начните вводить для поиска клиента...',
    next_add_products: 'Далее: Добавить продукты',
    step_products: 'Шаг 2: Сопоставление продуктов и количество',
    issuing_to: 'Выдача для:',
    row_total: 'Итого по строке',
    select_product: 'Выберите продукт...',
    add_next_product: 'Добавить следующий продукт',
    items_count: 'Кол-во предметов',
    target_balance_after: 'Целевой баланс после',
    next_review: 'Далее: Просмотр и подтверждение',
    step_review: 'Шаг 3: Финальный просмотр',
    account_update_summary: 'Сводка обновления аккаунта',
    points_to_add: 'Баллов к добавлению:',
    new_total_balance: 'Новый общий баланс:',
    product_breakdown: 'Разбивка по продуктам',
    issuance_reason_placeholder: 'Причина выдачи (например: Компенсация за задержку заказа...)',
    safety_confirmation: 'Требуется подтверждение безопасности',
    safety_confirmation_desc: 'Это действие немедленно обновит баланс баллов клиента. Записи будут созданы в журнале аудита для подотчетности.',
    safety_confirmation_label: 'Я подтверждаю, что все детали верны, и верифицирую эту выдачу баллов.',
    back_to_edit: 'Вернуться к редактированию',
    confirm_add_points: 'Подтвердить и добавить баллы',
    min: 'Мин',
    max: 'Макс',
    points_range: 'Диапазон баллов',
    earned_range: 'Диапазон заработанного',
    redeemed_range: 'Диапазон обмененого',
    add_points_modal: 'Добавить баллы на счет',
    amount: 'Сумма',
    reason: 'Причина',
    prev: 'Пред.',
    showing: 'Показано',
    of: 'из',
    totals: 'Итоги',
    reconciliation: 'Сверка по баллам',
    period_from: 'Дата от',
    period_to: 'Дата до',
    opening_balance: 'Остаток на начало',
    closing_balance: 'Остаток на конец',
    total_earned_period: 'Начислено всего',
    total_spent_period: 'Списано всего',
    order_count: 'Кол-во заказов',
    gift_count: 'Кол-во подарков',
    document_name: 'Название документа',
    earned_dt: 'Начислено (ДТ)',
    spent_kt: 'Списано (КТ)',
    balance_after: 'Баланс после операции',
    total_for_period: 'ВСЕГО за период',
    print: 'Печать',
    export_pdf: 'Экспорт PDF',
    edit_order: 'Редактировать заказ',
    delete_order: 'Удалить заказ',
    view_order: 'Просмотр заказа',
    old_total: 'Старый итог',
    new_total: 'Новый итог',
    difference: 'Разница',
    change_reason: 'Причина изменения',
    change_impact: 'Изменение затронет баланс клиента на:',
    delete_confirmation_draft: 'Удалить заказ {id}? Действие нельзя отменить.',
    delete_confirmation_confirmed: 'При удалении будет списано {points} баллов у клиента.',
    understand_balance_change: 'Я понимаю, что баланс изменится.',
    confirm_delete: 'Подтвердить удаление',
    all: 'Все',
    request_id: 'ID запроса',
    balance_after_redemption: 'Остаток баллов',
    gift: 'Подарок',
    bulk_approve: 'Массовое одобрение',
    bulk_reject: 'Массовое отклонение',
    process_timeline: 'Хронология действий',
    client_balance_info: 'Баланс клиента',
    confirm_status_change: 'Подтвердите смену статуса',
    status_change_warning: 'Это повлияет на баллы и склад.',
    available_points: 'Доступно баллов',
    out_of_stock: 'Нет в наличии',
    selected: 'выбрано',
    unit: 'шт.',
    request_initiated: 'Заявка создана',
    transitioned_to: 'Статус изменен на',
    processed_by: 'Обработал',
    confirm_action_correct: 'Я подтверждаю правильность действия.',
    reject_reason_placeholder: 'Укажите причину отказа...',
    audit_log: 'Журнал аудита',
    company_name: 'Название компании',
    points_name: 'Название баллов (напр. Кредиты)',
    points_expiry: 'Срок жизни баллов (мес)',
    min_redemption: 'Мин. сумма обмена',
    admin_roles: 'Роли админов',
    add_admin: 'Добавить админа',
    activity_type: 'Тип активности',
    details: 'Детали',
    user_agent: 'User Agent',
    ip_address: 'IP-адрес',
  },
  UZ: {
    dashboard: 'Boshqaruv paneli',
    customers: 'Mijozlar',
    orders: 'Ballar buyurtmasi',
    gifts: 'Sovg\'alar',
    products: 'Mahsulotlar',
    requests: 'Almashish so\'rovlari',
    audit: 'Audit jurnali',
    admin: 'Admin',
    user: 'Foydalanuvchi',
    switch_to_portal: 'Mijoz portaliga o\'tish',
    jump_to: 'O\'tish...',
    operational_insights: 'Operatsion ko\'rsatkichlar',
    track_manage_loyalty: 'Sodiqlik dasturini kuzatib boring va boshqaring',
    filter_period: 'Davr filtri',
    add_entity: 'Ob\'ekt qo\'shish',
    total_customers: 'Jami mijozlar',
    points_issued: 'Berilgan ballar',
    redemptions: 'Almashuvlar',
    pending_requests: 'Kutilayotgan so\'rovlar',
    points_movement: 'Ballar harakati vaqt bo\'yicha',
    issued: 'Berilgan',
    redeemed: 'Almashilgan',
    gift_categories: 'Sovg\'a toifalari',
    total_items: 'Jami buyumlar',
    audit_activity: 'Audit va faollik',
    view_full_log: 'To\'liq jurnal',
    top_earners: 'Eng ko\'p ball to\'plaganlar',
    earned_this_month: 'Shu oyda to\'plangan',
    total_points: 'Jami ballar',
    vs_last_month: 'o\'tgan oyga nisbatan',
    search_placeholder: 'Mijozlarni qidirish...',
    add_customer: 'Mijoz qo\'shish',
    export: 'Eksport',
    full_name: 'FIO',
    phone: 'Telefon',
    status: 'Holat',
    last_updated: 'Yangilangan',
    actions: 'Harakatlar',
    active: 'Faol',
    blocked: 'Bloklangan',
    points: 'Ballar',
    earned: 'To\'plangan',
    all_customers: 'Barcha mijozlar',
    customer_details: 'Mijoz tafsilotlari',
    edit: 'Tahrirlash',
    block: 'Bloklash',
    unblock: 'Blokdan chiqarish',
    delete: 'O\'chirish',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    confirm: 'Tasdiqlash',
    draft: 'Qoralama',
    confirmed: 'Tasdiqlangan',
    cancelled: 'Bekor qilingan',
    pending: 'Kutilmoqda',
    approved: 'Tasdiqlangan',
    rejected: 'Rad etilgan',
    shipped: 'Yuborilgan',
    completed: 'Yakunlangan',
    date: 'Sana',
    customer: 'Mijoz',
    items: 'Mahsulotlar',
    created_by: 'Tomonidan yaratilgan',
    new_order: 'Yangi buyurtma',
    gift_name: 'Sovg\'a nomi',
    points_used: 'Ishlatilgan ballar',
    operator: 'Operator',
    type: 'Turi',
    reject_reason: 'Rad etish sababi',
    approve: 'Tasdiqlash',
    reject: 'Rad etish',
    stock: 'Ombor',
    category: 'Toifa',
    points_cost: 'Narxi (ball)',
    is_active: 'Faol',
    add_gift: 'Sovg\'a qo\'shish',
    add_product: 'Mahsulot qo\'shish',
    points_value: 'Qiymati (ball)',
    my_points: 'Mening ballarim',
    available_gifts: 'Mavjud sovg\'alar',
    redeem: 'Almashish',
    my_requests: 'Mening so\'rovlarim',
    welcome_back: 'Xush kelibsiz',
    logout: 'Chiqish',
    switch_view: 'Ko\'rinishni o\'zgartirish',
    history: 'Tarix',
    no_data: 'Ma\'lumot topilmadi',
    loading: 'Yuklanmoqda...',
    success: 'Muvaffaqiyat',
    error: 'Xato',
    new_request: 'Yangi almashish so\'rovi',
    manual_issuance: 'Qo\'lda operatsion berish',
    select_customer: 'Mijozni tanlang',
    select_gift: 'Sovg\'ani tanlang',
    confirmation: 'Dastlabki ko\'rinish',
    back: 'Orqaga',
    next: 'Keyingi',
    create_approve: 'Yaratish va tasdiqlash',
    operational_queue: 'Operatsion navbat',
    manage_lifecycle: 'Almashish hayotiy tsiklini va qo\'lda so\'rovlarni boshqarish',
    new_manual_request: 'Yangi qo\'lda so\'rov',
    queue_inspector: 'Navbat inspektori',
    select_request_sidebar: 'Tafsilotlarni ko\'rish va jarayonlarni boshqarish uchun yon paneldan so\'rovni tanlang.',
    confirm_approval: 'Tasdiqlashni tasdiqlang',
    execute_approval: 'Tasdiqlashni bajarish',
    request_rejection: 'So\'rovni rad etish',
    specify_reject_reason: 'Iltimos, rad etish sababini ko\'rsating. Mijoz xabardor qilinadi.',
    confirm_reject: 'Rad etishni tasdiqlash',
    insufficient_points: 'Ballar yetarli emas',
    low_stock: 'Omborda kam',
    product_mapping: 'Mahsulotlarni bog\'lash',
    assign_points: 'IRIZON tijorat mahsulotlariga ball qiymatlarini tayinlash',
    bonus_value: 'Bonus qiymati',
    bonus_issuance: 'Bonus ballarini berish',
    manage_bonus: 'Mijoz hisoblariga qo\'lda bonus qo\'shishni boshqarish',
    export_orders: 'Buyurtmalarni eksport qilish',
    create_bonus_order: 'Bonus buyurtmasini yaratish',
    filter_status: 'Holat filtri',
    all_admins: 'Barcha adminlar',
    order_id: 'Buyurtma ID',
    date_time: 'Sana / Vaqt',
    points_added: 'Qo\'shilgan ballar',
    order_details: 'Buyurtma tafsilotlari',
    products_issued: 'Berilgan mahsulotlar',
    unit_points: 'Birlik ballari',
    qty: 'Soni',
    total: 'Jami',
    grand_total: 'Umumiy jami',
    admin_note: 'Admin eslatmasi',
    duplicate_order: 'Buyurtmani nusxalash',
    confirm_now: 'Hozir tasdiqlash',
    bonus_workflow: 'Bonus berish jarayoni',
    step_customer: '1-qadam: Mijozni tanlang',
    active_selection: 'Faol tanlov',
    current_balance: 'Joriy balans',
    lifetime_earned: 'Jami to\'plangan',
    last_activity: 'Oxirgi faollik',
    no_customers_found: 'Mijoz topilmadi',
    type_to_search: 'Mijozni qidirish uchun yozing...',
    next_add_products: 'Keyingi: Mahsulotlarni qo\'shish',
    step_products: '2-qadam: Mahsulotlar va miqdor',
    issuing_to: 'Berilmoqda:',
    row_total: 'Satr jami',
    select_product: 'Mahsulotni tanlang...',
    add_next_product: 'Keyingi mahsulotni qo\'shish',
    items_count: 'Mahsulotlar soni',
    target_balance_after: 'Keyingi balans',
    next_review: 'Keyingi: Ko\'rib chiqish va tasdiqlash',
    step_review: '3-qadam: Yakuniy ko\'rib chiqish',
    account_update_summary: 'Hisobni yangilash xulosasi',
    points_to_add: 'Qo\'shiladigan ballar:',
    new_total_balance: 'Yangi umumiy balans:',
    product_breakdown: 'Mahsulotlar taqsimoti',
    issuance_reason_placeholder: 'Berish sababi (masalan: Buyurtma kechikkani uchun kompensatsiya...)',
    safety_confirmation: 'Xavfsizlik tasdig\'i talab qilinadi',
    safety_confirmation_desc: 'Ushbu harakat mijozning ball balansini darhol yangilaydi. Hisobdorlik uchun audit jurnalida yozuvlar yaratiladi.',
    safety_confirmation_label: 'Barcha tafsilotlar to\'g\'riligini tasdiqlayman va ushbu ball berishni verifikatsiya qilaman.',
    back_to_edit: 'Tahrirlashga qaytish',
    confirm_add_points: 'Tasdiqlash va ballarni qo\'shish',
    min: 'Min',
    max: 'Maks',
    points_range: 'Ballar oralig\'i',
    earned_range: 'To\'plangan ballar oralig\'i',
    redeemed_range: 'Almashilgan ballar oralig\'i',
    add_points_modal: 'Hisobga ball qo\'shish',
    amount: 'Miqdor',
    reason: 'Sabab',
    prev: 'Oldingi',
    showing: 'Ko\'rsatilmoqda',
    of: 'dan',
    totals: 'Jami',
    reconciliation: 'Ballar bo\'yicha solishtirish',
    period_from: 'Sana dan',
    period_to: 'Sana gacha',
    opening_balance: 'Boshlang\'ich qoldiq',
    closing_balance: 'Yakuniy qoldiq',
    total_earned_period: 'Jami to\'plangan',
    total_spent_period: 'Jami ishlatilgan',
    order_count: 'Buyurtmalar soni',
    gift_count: 'Sovg\'alar soni',
    document_name: 'Hujjat nomi',
    earned_dt: 'To\'plangan (DT)',
    spent_kt: 'Ishlatilgan (KT)',
    balance_after: 'Operatsiyadan keyingi balans',
    total_for_period: 'Davr uchun JAMI',
    print: 'Chop etish',
    export_pdf: 'PDF eksport',
    audit_log: 'Audit jurnali',
    company_name: 'Kompaniya nomi',
    points_name: 'Ballar nomi (masalan: Kreditlar)',
    points_expiry: 'Ballar muddati (oy)',
    min_redemption: 'Minimal almashish miqdori',
    admin_roles: 'Admin rollari',
    add_admin: 'Admin qo\'shish',
    activity_type: 'Faollik turi',
    details: 'Tafsilotlar',
    user_agent: 'User Agent',
    ip_address: 'IP manzil',
  }
};

export const DUMMY_CUSTOMERS: Customer[] = [
  { id: 'C-1001', fullName: 'Alexander Petrov', phone: '+998 90 123 45 67', totalPoints: 4500, pointsEarned: 12000, pointsRedeemed: 7500, status: 'active', lastUpdated: '2023-11-20' },
  { id: 'C-1002', fullName: 'Dilshod Karimov', phone: '+998 93 321 65 43', totalPoints: 1200, pointsEarned: 5000, pointsRedeemed: 3800, status: 'active', lastUpdated: '2023-11-21' },
  { id: 'C-1003', fullName: 'Elena Ivanova', phone: '+998 94 999 00 11', totalPoints: 8900, pointsEarned: 15000, pointsRedeemed: 6100, status: 'blocked', lastUpdated: '2023-11-19' },
  { id: 'C-1004', fullName: 'Azizbek Toshpulotov', phone: '+998 97 777 88 99', totalPoints: 340, pointsEarned: 1000, pointsRedeemed: 660, status: 'active', lastUpdated: '2023-11-22' },
];

export const DUMMY_GIFTS: GiftType[] = [
  { 
    id: 'G-2001', 
    name: { EN: 'Premium Thermos', RU: 'Премиум термос', UZ: 'Premium termos' },
    description: { EN: 'Keep your drinks hot for 24h.', RU: 'Сохраняет напитки горячими 24ч.', UZ: 'Ichimliklarni 24 soat issiq saqlaydi.' },
    pointsCost: 500, category: 'Lifestyle', stock: 12, isActive: true, image: 'https://picsum.photos/400/300?random=1' 
  },
  { 
    id: 'G-2002', 
    name: { EN: 'Wireless Headphones', RU: 'Беспроводные наушники', UZ: 'Simsiz quloqchinlar' },
    description: { EN: 'High fidelity audio.', RU: 'Высококачественный звук.', UZ: 'Yuqori sifatli ovoz.' },
    pointsCost: 1200, category: 'Tech', stock: 5, isActive: true, image: 'https://picsum.photos/400/300?random=2' 
  },
  { 
    id: 'G-2003', 
    name: { EN: 'Leather Notebook', RU: 'Кожаный блокнот', UZ: 'Charm daftar' },
    description: { EN: 'A5 Genuine leather cover.', RU: 'А5 Обложка из натуральной кожи.', UZ: 'A5 Tabiiy charm muqova.' },
    pointsCost: 300, category: 'Stationary', stock: 0, isActive: false, image: 'https://picsum.photos/400/300?random=3' 
  },
];

export const DUMMY_PRODUCTS: Product[] = [
  { id: 'P-3001', name: { EN: 'Solar Panel X5', RU: 'Солнечная панель X5', UZ: 'Quyosh paneli X5' }, pointsValue: 50, isActive: true, category: 'Energy' },
  { id: 'P-3002', name: { EN: 'Smart Inverter Pro', RU: 'Умный инвертор Pro', UZ: 'Aqlli invertor Pro' }, pointsValue: 120, isActive: true, category: 'Electronics' },
];

export const DUMMY_REQUESTS: RedemptionRequest[] = [
  { id: 'REQ-5001', date: '2023-11-22 14:30', customerId: 'C-1001', customerName: 'Alexander Petrov', giftId: 'G-2001', giftName: 'Premium Thermos', pointsUsed: 500, status: 'Pending', requestType: 'Customer', giftImage: 'https://picsum.photos/400/300?random=1' },
  { id: 'REQ-5002', date: '2023-11-21 09:15', customerId: 'C-1002', customerName: 'Dilshod Karimov', giftId: 'G-2002', giftName: 'Wireless Headphones', pointsUsed: 1200, status: 'Approved', operator: 'Admin-Z', requestType: 'Customer', giftImage: 'https://picsum.photos/400/300?random=2' },
  { id: 'REQ-5003', date: '2023-11-20 18:00', customerId: 'C-1004', customerName: 'Azizbek Toshpulotov', giftId: 'G-2003', giftName: 'Leather Notebook', pointsUsed: 300, status: 'Rejected', operator: 'Admin-X', rejectReason: 'Out of stock indefinitely.', requestType: 'Customer', giftImage: 'https://picsum.photos/400/300?random=3' },
  { id: 'REQ-5004', date: '2023-11-23 11:00', customerId: 'C-1004', customerName: 'Azizbek Toshpulotov', giftId: 'G-2002', giftName: 'Wireless Headphones', pointsUsed: 1200, status: 'Pending', requestType: 'Admin', giftImage: 'https://picsum.photos/400/300?random=2' },
];

export const DUMMY_ORDERS: Order[] = [
  {
    id: 'ORD-9001',
    date: '2023-11-22 10:00',
    customerId: 'C-1001',
    customerName: 'Alexander Petrov',
    totalPoints: 1500,
    itemsCount: 2,
    createdBy: 'Admin-X',
    status: 'Confirmed',
    items: [
      { id: 'ITM-1', productId: 'P-3001', productName: 'Solar Panel X5', pointsPerUnit: 50, quantity: 10, totalPoints: 500 },
      { id: 'ITM-2', productId: 'P-3002', productName: 'Smart Inverter Pro', pointsPerUnit: 120, quantity: 8, totalPoints: 1000 },
    ]
  },
  {
    id: 'ORD-9002',
    date: '2023-11-22 11:30',
    customerId: 'C-1002',
    customerName: 'Dilshod Karimov',
    totalPoints: 250,
    itemsCount: 1,
    createdBy: 'Admin-Z',
    status: 'Draft',
    items: [
      { id: 'ITM-3', productId: 'P-3001', productName: 'Solar Panel X5', pointsPerUnit: 50, quantity: 5, totalPoints: 250 },
    ]
  },
  {
    id: 'ORD-9003',
    date: '2023-10-15 09:00',
    customerId: 'C-1001',
    customerName: 'Alexander Petrov',
    totalPoints: 5000,
    itemsCount: 1,
    createdBy: 'Admin-X',
    status: 'Confirmed',
    items: [
      { id: 'ITM-4', productId: 'P-3002', productName: 'Smart Inverter Pro', pointsPerUnit: 120, quantity: 42, totalPoints: 5040 },
    ]
  },
  {
    id: 'ORD-9004',
    date: '2023-09-01 14:00',
    customerId: 'C-1001',
    customerName: 'Alexander Petrov',
    totalPoints: 2000,
    itemsCount: 1,
    createdBy: 'Admin-Z',
    status: 'Confirmed',
    items: [
      { id: 'ITM-5', productId: 'P-3001', productName: 'Solar Panel X5', pointsPerUnit: 50, quantity: 40, totalPoints: 2000 },
    ]
  }
];

export const DUMMY_ACTIVITIES: Activity[] = [
  { id: 'ACT-001', type: 'customer_added', description: 'New customer Elena Ivanova added to system', time: '2 hours ago', user: 'Admin-X' },
  { id: 'ACT-002', type: 'gift_redeemed', description: 'Alexander Petrov redeemed Wireless Headphones', time: '5 hours ago', user: 'System' },
  { id: 'ACT-003', type: 'request_status_change', description: 'Request REQ-5002 approved by Admin-Z', time: '1 day ago', user: 'Admin-Z' },
  { id: 'ACT-004', type: 'order_confirmed', description: 'Bonus order ORD-9001 confirmed for Alexander Petrov', time: '2 days ago', user: 'Admin-X' },
];

export const STATUS_CONFIG = {
  Pending: { color: 'bg-amber-100 text-amber-700 border-amber-200', icon: <Clock className="w-3 h-3" /> },
  Approved: { color: 'bg-emerald-100 text-emerald-700 border-emerald-200', icon: <CheckCircle2 className="w-3 h-3" /> },
  Rejected: { color: 'bg-rose-100 text-rose-700 border-rose-200', icon: <XCircle className="w-3 h-3" /> },
  Shipped: { color: 'bg-blue-100 text-blue-700 border-blue-200', icon: <Truck className="w-3 h-3" /> },
  Completed: { color: 'bg-slate-100 text-slate-700 border-slate-200', icon: <CheckCircle2 className="w-3 h-3" /> },
};
